### ISSUE TITLE
Highway rendering problem

### ISSUE THREAD

**Issue by amalvarenga** [sozialhelden/wheelmap-react-frontend#201]
https://www.openstreetmap.org/way/51965774

OSM screenshot:
![junction-circular-bug-OSM](https://user-images.githubusercontent.com/5130776/57196720-e2c4aa00-6f35-11e9-8dff-f4671a46899e.png)

Wheelmap screenshot:
![junction-circular-bug-wheelmap](https://user-images.githubusercontent.com/5130776/57196731-eeb06c00-6f35-11e9-9a3c-7106c52b4059.png)

I'm not sure if this problem is related to junction=circular use.

**Comment by opyh** [comment]
This is because the roundabout seems not to be correctly mapped on OSM. It's simply a circle and does not connect the ways that are connected to it.

Here is an explanation how it should be mapped: https://labs.mapbox.com/mapping/mapping-for-navigation/circular-junctions/
