### ISSUE TITLE
Changeset bounding box area

### ISSUE THREAD

**Issue by Lee-Carre** [sozialhelden/wheelmap-react-frontend#327]
#### Describe the bug
Since it was never resolved before the [wheelmap-classic](/sozialhelden/wheelmap-classic) repo was retired: [#29: “Split your OSM-changesets by wheelmap_visitor into much smaller areas”](/sozialhelden/wheelmap-classic/issues/29).

#### To Reproduce
1. See [changesets by wheelmap_visitor](//www.openstreetmap.org/user/wheelmap_visitor/history) for plenty of examples of excessively large bounding boxes.
2. See [comments on wheelmap_visitor's changesets](//resultmaps.neis-one.org/osm-discussion-comments?uid=290680) for examples of other mappers adversely affected by this misbehaviour.

#### Expected behavior
Compliance with [OSM Wiki § Changesets § Geographical size of changesets](//wiki.openstreetmap.org/wiki/Changeset#Geographical_size_of_changesets).

#### Software in use:
* rosemary v0.4.4

**Comment by opyh** [comment]
https://github.com/sozialhelden/wheelmap-frontend/issues/329#issuecomment-988260543

**Comment by sebicodes** [comment]
I just want to emphasize that it is an urgent issue. The history tool of the primary website www.openstreetmap.org is hardly usable any more because at any place there is an overlap with lots of wheelmap_visitor changesets, that are distributed all over the world!

**Comment by opyh** [comment]
The PR mentioned above will create small, atomic changesets. It's not in a deployable state yet, but will be soon. There will be a public beta deployment to test this feature soon. I'm sorry that all this took so long already.

**Comment by opyh** [comment]
Just a little update: we have implemented writing atomic changesets (= one edit per changeset) in the new branch.

Will post an update again when this is deployed as a beta.

**Comment by opyh** [comment]
Here is an update on this: Our beta release at https://feature-attach-osm-api.wheelmap.tech/ writes changesets with one edit per changeset. The deployment still contains some known UX issues – when they are fixed, this change will go into production.

**Comment by opyh** [comment]
The beta deployment is online ([blog post](https://news.wheelmap.org/en/improved-wheelmap-test-it-now-and-rate-even-more-places/), [beta.wheelmap.org](https://beta.wheelmap.org)). Waiting for community feedback, then this will go into production.

**Comment by opyh** [comment]
This seems to work reliably. Please reopen if you see something that I might have missed.
